sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
env:
  global:
    - PATH=$PATH:$HOME/google-cloud-sdk/bin
    - PROJECT_ID="gsrc-lords"
    - ZONE="europe-west1-b"
    - IMAGE_NAME=demo:latest
    - FULL_IMAGE_NAME=gcr.io/$PROJECT_ID/$IMAGE_NAME
    - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json"
    - CLUSTER_NAME=backend-cluster
before_install:
- openssl aes-256-cbk -K $encrypted_142535234c_key -iv $encrypted_12323423423440c_in -in client-secret.json.
  - chmod +x gcloud-sdk-instal.sh
  - ./gcloud-sdk-install.sh
  - source /home/travis/.bashrc
  - chmod +x gcloud-sdk-configure.sh
  - ./gcloud-sdk-configure.sh
install: true
before_script:
  - chmod +x image-prepare.sh
  - chmod +x image-push.sh
  - chmod +x gcloud-select-cluster.sh
  - ./image-prepare.sh $FULL_IMAGE_NAME
  - ./image-push.sh $FULL_IMAGE_NAME
script:
  - ./gcloud-select-cluster.sh $CLUSTER_NAME