sudo: required
language: java
jdk:
- oraclejdk8
deploy:
  provider: gae
  project: gsrc-lords
before_install:
- openssl aes-256-cbc -K $encrypted_de917ce340da_key -iv $encrypted_de917ce340da_iv
  -in client-secret.json.enc -out client-secret.json -d
