apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lords
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        revision: "{{CF_REVISION}}"
      labels:
        app: api-svc
    spec:
      containers:
        - name: lords
          image: lords:{{CF_BRANCH}}
          ports:
            - containerPort: 80
              name: http